---
- name: Converge
  hosts: all
  become: true

  vars:
    git_repos:
      - url: github.com/sorrowless/ansible_git.git
        dest: /tmp/ansible_git

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'

  roles:
    - role: git
